name: phishing-ml-env
channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.10
  - numpy=1.26
  - pandas=2.1
  - scikit-learn=1.3
  - xgboost=1.7
  - joblib=1.3
  - flask=2.3
  - requests
  - scrapy
  - beautifulsoup4
  - lxml
  - jupyterlab
  - ipykernel
  - matplotlib
  - seaborn
  - pip
  - pip:
      - imbalanced-learn==0.12
      - tldextract==5.1.1
